enum ServicePath {
  USERLOGIN,
  USERCREATE,
  COMPANYCREATE,
  COMPANYUPDATE,
  COMPANYGET,
  USERLIST,
  PRODUCTALL,
  PRODUCTCREATE,
  PRODUCTSEARCH,
  PRODUCTUPDATE,
  RECEIPTCREATE,
  RECEIPTLIST,
  SUPPLIERCREATE,
  SUPPLIERLIST
}
